"""One-line summaries of vv sessions, generated by an agent CLI.

Powers the descriptions shown next to each session in the "list existing
sessions" menu. A summary is produced by handing the session's git state (or,
for a chat session, its file list) to an agent CLI run in non-interactive
"print" mode and keeping the first line it prints. Everything here is
best-effort: any failure just means that session shows no summary.
"""

from __future__ import annotations

import json
import re
import shlex
import subprocess
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

from . import agents, config, git_ops

#: Tokens inserted between an agent command and the prompt to run it in
#: non-interactive "print" mode (read one prompt, print the answer, and exit),
#: keyed by command name — mirroring :data:`agents.BYPASS_FLAGS`.
#:
#: ONLY ``claude``'s tokens are verified. The others are best-guesses — check
#: each CLI's own ``--help``. A command absent from this map is treated as
#: unable to summarize (vv would rather show nothing than launch an interactive
#: agent that hangs waiting for input).
PRINT_FLAGS: dict[str, tuple[str, ...]] = {
    "claude": ("-p",),
    "codex": ("exec",),   # VERIFY
    "gemini": ("-p",),    # VERIFY
    "copilot": ("-p",),   # VERIFY
}

#: How long to wait for a single session's summary before giving up on it.
TIMEOUT_SECONDS = 60.0

#: Cap on concurrent summary subprocesses.
MAX_WORKERS = 8

#: Per-agent transcript stores. Reading these is what lets an uncommitted
#: session still be summarized. vv doesn't record which agent ran a session, so
#: :func:`_transcript_context` probes each store in turn (Claude, then Gemini,
#: then Codex) and uses the first that yields a conversation.
#:
#: - Claude: one dir per working directory under ``CLAUDE_PROJECTS_DIR``, named
#:   by the path with every non-alphanumeric char turned into ``-``.
#: - Gemini: ``GEMINI_PROJECTS_FILE`` maps a working directory to a short tag,
#:   whose chats live in ``GEMINI_TMP_DIR/<tag>/chats/session-*.json``.
#: - Codex: flat, date-bucketed ``rollout-*.jsonl`` files under
#:   ``CODEX_SESSIONS_DIR``, each carrying its own ``cwd`` in a header line.
CLAUDE_PROJECTS_DIR = Path.home() / ".claude" / "projects"
GEMINI_PROJECTS_FILE = Path.home() / ".gemini" / "projects.json"
GEMINI_TMP_DIR = Path.home() / ".gemini" / "tmp"
CODEX_SESSIONS_DIR = Path.home() / ".codex" / "sessions"

#: Cap on how many Codex rollout files to inspect when matching a session's cwd
#: (they accumulate over time; we scan newest-first and stop at the first match).
CODEX_SCAN_LIMIT = 500

#: How much recent conversation text to feed the summary agent, and per-message.
MAX_TRANSCRIPT_CHARS = 2500
MAX_MESSAGE_CHARS = 500
#: How many of the most-recent real messages to include (plus the first one).
RECENT_MESSAGES = 6

#: Prefixes marking synthetic user turns (slash/bash commands, tool results,
#: injected reminders) rather than something the human actually said.
_SKIP_PREFIXES = (
    "<local-command",
    "<bash-input",
    "<bash-stdout",
    "<bash-stderr",
    "<command-name",
    "<command-message",
    "<command-args",
    "<system-reminder",
    "[tool_result]",
    "[tool_use]",
    "Caveat:",
)

_PROMPT = (
    "Summarize in one terse line (at most 12 words, no trailing period) what "
    "this coding session is working on, based only on the git state and agent "
    "conversation below. Reply with the summary line and nothing else.\n\n"
)

#: Stable opening of :data:`_PROMPT`. An agent transcript whose first user
#: message begins with this is one of vv's *own* summary runs — we skip those
#: when reading a session's history so summaries never feed on themselves.
_SUMMARY_MARKER = "Summarize in one terse line"


def can_summarize(agent: str) -> bool:
    """Return True if vv knows how to run ``agent`` non-interactively."""
    return agents.command_of(agent) in PRINT_FLAGS


def summarize(agent: str, path: Path) -> str | None:
    """Return a one-line summary of the session at ``path``, or ``None``.

    Runs the summary ``agent`` in print mode inside ``path``, feeding it a
    compact snapshot of the session's git state (or file list for a chat
    session). Returns ``None`` when vv can't run ``agent`` non-interactively,
    there is no context worth summarizing, or the command fails / times out.
    """
    if not can_summarize(agent):
        return None
    context = _gather_context(path)
    if not context:
        return None
    argv = [*shlex.split(agent), *PRINT_FLAGS[agents.command_of(agent)], _PROMPT + context]
    try:
        result = subprocess.run(
            argv,
            # Run in a throwaway dir, NOT the session: agent CLIs persist a
            # transcript for whatever directory they run in, and writing into the
            # session's own transcript store would both pollute the history we
            # read back for context and invalidate its activity fingerprint on
            # every run (defeating the cache). All the context is in the prompt.
            cwd=_scratch_cwd() or str(path),
            text=True,
            capture_output=True,
            timeout=TIMEOUT_SECONDS,
            check=True,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    return _first_line(result.stdout)


def _scratch_cwd() -> str | None:
    """A stable throwaway directory to run summary agents in (see :func:`summarize`).

    Kept out of the worktree listing (a hidden dir under ``WORKTREES_DIR``) and
    of every session's transcript store. Returns ``None`` if it can't be created,
    in which case the caller falls back to the session dir.
    """
    scratch = config.worktrees_dir() / ".summary-scratch"
    try:
        scratch.mkdir(parents=True, exist_ok=True)
    except OSError:
        return None
    return str(scratch)


def summarize_all(agent: str, paths: dict[object, Path]) -> dict[object, str]:
    """Summarize many sessions in parallel, keyed by the caller's own keys.

    ``paths`` maps an opaque key (e.g. a ``(repo, name)`` tuple) to a session
    path; the result maps the same keys to their summaries, omitting sessions
    that produced no summary. Runs up to :data:`MAX_WORKERS` at a time.
    """
    if not paths or not can_summarize(agent):
        return {}
    summaries: dict[object, str] = {}
    with ThreadPoolExecutor(max_workers=min(len(paths), MAX_WORKERS)) as pool:
        futures = {key: pool.submit(summarize, agent, path) for key, path in paths.items()}
    for key, future in futures.items():
        try:
            text = future.result()
        except Exception:  # noqa: BLE001 — one bad session must not sink the rest
            text = None
        if text:
            summaries[key] = text
    return summaries


# --- caching ----------------------------------------------------------------
#
# Summarizing spawns an agent subprocess per session — too slow to redo on every
# menu open. We cache each session's summary keyed by a cheap *activity
# fingerprint* (its dir mtime + the driving transcript file's mtime), so a
# summary is only regenerated once the session has actually changed — i.e. been
# opened and worked in — since it was last summarized.

#: Bump when the cache entry shape changes, to discard stale on-disk caches.
CACHE_VERSION = 1


def session_fingerprint(path: Path) -> str:
    """A cheap token that changes whenever the session has seen activity.

    Combines the session directory's mtime with the mtime (and identity) of the
    transcript that drives its summary — the latter advances on every agent
    turn, so any real work in the session invalidates a cached summary. All from
    ``stat`` calls; no agent is run.
    """
    transcript = _transcript_path(path)
    tpart = f"{transcript}@{_mtime_ns(transcript)}" if transcript is not None else "-"
    return f"{_mtime_ns(path)}|{tpart}"


def load_cache() -> dict[str, dict]:
    """Load the on-disk summary cache as ``{session_id: {agent, fingerprint, summary}}``.

    Returns ``{}`` on a missing, unreadable, or version-mismatched cache — a
    stale cache is never a hard error, just a full regeneration.
    """
    try:
        with config.summary_cache_file().open(encoding="utf-8") as handle:
            data = json.load(handle)
    except (OSError, json.JSONDecodeError, ValueError):
        return {}
    if not isinstance(data, dict) or data.get("version") != CACHE_VERSION:
        return {}
    sessions = data.get("sessions")
    return sessions if isinstance(sessions, dict) else {}


def save_cache(sessions: dict[str, dict]) -> None:
    """Write the summary cache, atomically and best-effort (failures ignored)."""
    path = config.summary_cache_file()
    tmp = path.with_name(path.name + ".tmp")
    try:
        with tmp.open("w", encoding="utf-8") as handle:
            json.dump({"version": CACHE_VERSION, "sessions": sessions}, handle)
        tmp.replace(path)
    except OSError:
        pass


def _mtime_ns(path: Path) -> int:
    """Return ``path``'s modification time in ns, or 0 if it can't be stat'd."""
    try:
        return path.stat().st_mtime_ns
    except OSError:
        return 0


def _gather_context(path: Path) -> str:
    """Build the text handed to the agent to summarize this session.

    Combines two sources so a session is summarizable even before anything is
    committed: the git state (or file list for a chat) *and* the recent agent
    conversation from the session's transcript. Either may be empty.
    """
    sections: list[str] = []
    base = _git_context(path) if (path / ".git").exists() else _dir_context(path)
    if base:
        sections.append(base)
    transcript = _transcript_context(path)
    if transcript:
        sections.append("Recent agent conversation:\n" + transcript)
    return "\n\n".join(sections)


def _git_context(path: Path) -> str:
    """Compact snapshot of a git worktree: branch, session commits, changes."""
    sections: list[str] = []
    try:
        branch = git_ops.current_branch(path)
        if branch:
            sections.append(f"Branch: {branch}")
    except git_ops.GitError:
        pass
    try:
        log = git_ops.log_oneline(path, limit=20, unpushed_only=True)
        if log:
            sections.append("Commits made in this session:\n" + log)
    except git_ops.GitError:
        pass
    try:
        status = git_ops.status_porcelain(path)
        if status:
            sections.append("Uncommitted changes:\n" + status)
    except git_ops.GitError:
        pass
    try:
        diff = git_ops.diff_stat(path)
        if diff:
            sections.append("Diff against HEAD:\n" + diff)
    except git_ops.GitError:
        pass
    return "\n\n".join(sections)


def _dir_context(path: Path) -> str:
    """File listing for a chat session (no git worktree to describe)."""
    try:
        names = sorted(p.name for p in path.iterdir())
    except OSError:
        return ""
    if not names:
        return ""
    return "Files in this chat session directory:\n" + "\n".join(names[:50])


def _encode_project_path(path: Path) -> str:
    """Encode a working directory the way Claude names its transcript dir.

    Every character that is not a letter or digit becomes ``-`` (so ``/``,
    ``.`` and ``_`` all collapse to ``-``), matching the folders Claude creates
    under :data:`CLAUDE_PROJECTS_DIR`.
    """
    return re.sub(r"[^a-zA-Z0-9]", "-", str(path))


def _transcript_context(path: Path) -> str:
    """Extract a compact snippet of the session's recent agent conversation.

    vv doesn't track which agent ran a session, so each store is probed in turn
    — Claude, then Gemini, then Codex — and the first that yields a conversation
    wins (later agents aren't checked). Each provider returns ``(role, text)``
    pairs of genuine user/assistant turns (tool calls, tool results, and
    synthetic command turns filtered out); :func:`_render_messages` then keeps
    the first (the task) plus the last few (recent progress). Empty when no store
    has a transcript for this session, so callers fall back to git/file context.
    """
    for provider in (_claude_messages, _gemini_messages, _codex_messages):
        try:
            messages = provider(path)
        except OSError:
            messages = []
        rendered = _render_messages(messages)
        if rendered:
            return rendered
    return ""


def _transcript_path(path: Path) -> Path | None:
    """The transcript file that drives this session's summary, in probe order.

    Mirrors :func:`_transcript_context`'s Claude → Gemini → Codex order, but only
    *locates* the file (no parsing) — used to fingerprint session activity
    cheaply, since the file's mtime advances every time the agent does something.
    """
    for finder in (_claude_file, _gemini_file, _codex_file):
        try:
            found = finder(path)
        except OSError:
            found = None
        if found is not None:
            return found
    return None


def _render_messages(messages: list[tuple[str, str]]) -> str:
    """Render the first + last-few messages into a bounded transcript snippet."""
    if not messages:
        return ""
    # First message pins the intent; the tail shows where it got to. The first
    # may also appear in the tail (short sessions), so dedup by value.
    picked = [messages[0], *messages[-RECENT_MESSAGES:]]
    seen: set[tuple[str, str]] = set()
    lines: list[str] = []
    used = 0
    for message in picked:
        if message in seen:
            continue
        seen.add(message)
        role, text = message
        entry = f"{role}: {text[:MAX_MESSAGE_CHARS]}"
        if used + len(entry) > MAX_TRANSCRIPT_CHARS:
            break
        lines.append(entry)
        used += len(entry)
    return "\n".join(lines)


def _window(messages: list[tuple[str, str]]) -> list[tuple[str, str]]:
    """Keep the first message plus the last :data:`RECENT_MESSAGES` (bounded)."""
    if len(messages) <= RECENT_MESSAGES + 1:
        return messages
    return [messages[0], *messages[-RECENT_MESSAGES:]]


# --- Claude: one JSONL file per session, dir named after the cwd ------------

def _claude_file(path: Path) -> Path | None:
    """Newest *real* Claude transcript for the session, skipping vv's own runs.

    A summary run (from before we isolated the scratch cwd, or under an older
    vv) leaves a transcript in the session's project dir; those are skipped so
    the summary reflects the actual session, not a previous summary of it.
    """
    project_dir = CLAUDE_PROJECTS_DIR / _encode_project_path(path)
    candidates = sorted(
        (p for p in project_dir.glob("*.jsonl") if p.is_file()),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    for candidate in candidates:
        if not _is_summary_run(candidate):
            return candidate
    return None


def _is_summary_run(transcript: Path) -> bool:
    """True if a Claude transcript's first user turn is one of vv's summary runs."""
    try:
        with transcript.open(encoding="utf-8", errors="replace") as handle:
            for line in handle:
                try:
                    obj = json.loads(line)
                except (json.JSONDecodeError, ValueError):
                    continue
                if isinstance(obj, dict) and obj.get("type") == "user":
                    text = _content_text(obj.get("message", {}).get("content")).strip()
                    return text.startswith(_SUMMARY_MARKER)
    except OSError:
        return False
    return False


def _claude_messages(path: Path) -> list[tuple[str, str]]:
    """Real user/assistant turns from the session's newest Claude transcript."""
    transcript = _claude_file(path)
    if transcript is None:
        return []
    messages: list[tuple[str, str]] = []
    with transcript.open(encoding="utf-8", errors="replace") as handle:
        for line in handle:
            try:
                obj = json.loads(line)
            except (json.JSONDecodeError, ValueError):
                continue
            if not isinstance(obj, dict) or obj.get("type") not in ("user", "assistant"):
                continue
            entry = _clean_turn(obj["type"], _content_text(obj.get("message", {}).get("content")))
            if entry:
                messages.append(entry)
    return _window(messages)


# --- Gemini: one JSON file per session under a per-project tag dir -----------

def _gemini_file(path: Path) -> Path | None:
    """Newest Gemini chat file for the session, if any."""
    tag = _gemini_tag(path)
    if tag is None:
        return None
    return _newest((GEMINI_TMP_DIR / tag / "chats").glob("session-*.json"))


def _gemini_messages(path: Path) -> list[tuple[str, str]]:
    """Real user/model turns from the session's newest Gemini chat file."""
    chats = _gemini_file(path)
    if chats is None:
        return []
    with chats.open(encoding="utf-8", errors="replace") as handle:
        try:
            obj = json.load(handle)
        except (json.JSONDecodeError, ValueError):
            return []
    messages: list[tuple[str, str]] = []
    for item in obj.get("messages", []) if isinstance(obj, dict) else []:
        if not isinstance(item, dict):
            continue
        # Gemini tags model turns "gemini"; anything else non-user (info, …) is
        # not conversation and is skipped.
        role = {"user": "user", "gemini": "assistant"}.get(item.get("type"))
        if role is None:
            continue
        entry = _clean_turn(role, _content_text(item.get("content")))
        if entry:
            messages.append(entry)
    return _window(messages)


def _gemini_tag(path: Path) -> str | None:
    """Look up the short tag Gemini assigns this working directory, if any."""
    try:
        with GEMINI_PROJECTS_FILE.open(encoding="utf-8") as handle:
            projects = json.load(handle).get("projects", {})
    except (OSError, json.JSONDecodeError, ValueError, AttributeError):
        return None
    if not isinstance(projects, dict):
        return None
    tag = projects.get(str(path)) or projects.get(str(path.resolve()))
    return tag if isinstance(tag, str) and tag else None


# --- Codex: flat, date-bucketed rollout files carrying their own cwd ---------

def _codex_file(path: Path) -> Path | None:
    """Newest Codex rollout whose recorded ``cwd`` is this session, if any."""
    return _codex_rollout_for(path)


def _codex_messages(path: Path) -> list[tuple[str, str]]:
    """Real user/agent turns from the newest Codex rollout matching this cwd."""
    transcript = _codex_file(path)
    if transcript is None:
        return []
    messages: list[tuple[str, str]] = []
    with transcript.open(encoding="utf-8", errors="replace") as handle:
        for line in handle:
            try:
                obj = json.loads(line)
            except (json.JSONDecodeError, ValueError):
                continue
            if not isinstance(obj, dict) or obj.get("type") != "event_msg":
                continue
            payload = obj.get("payload", {})
            # user_message / agent_message events already carry clean prose,
            # unlike the response_item blocks (which include system prompts and
            # the synthetic <environment_context> turn).
            role = {"user_message": "user", "agent_message": "assistant"}.get(
                payload.get("type")
            )
            if role is None:
                continue
            entry = _clean_turn(role, payload.get("message"))
            if entry:
                messages.append(entry)
    return _window(messages)


def _codex_rollout_for(path: Path) -> Path | None:
    """Find the newest Codex rollout whose recorded ``cwd`` is this session.

    Codex files don't encode the cwd in their name (it lives in a header line),
    so we scan the newest :data:`CODEX_SCAN_LIMIT` rollouts and read just each
    one's header until a ``cwd`` matches.
    """
    try:
        rollouts = sorted(
            (p for p in CODEX_SESSIONS_DIR.rglob("rollout-*.jsonl") if p.is_file()),
            key=lambda p: p.stat().st_mtime,
            reverse=True,
        )
    except OSError:
        return None
    wanted = {str(path), str(path.resolve())}
    for rollout in rollouts[:CODEX_SCAN_LIMIT]:
        if _codex_cwd(rollout) in wanted:
            return rollout
    return None


def _codex_cwd(rollout: Path) -> str | None:
    """Return the ``cwd`` from a Codex rollout's ``session_meta`` header line."""
    try:
        with rollout.open(encoding="utf-8", errors="replace") as handle:
            for line in handle:  # header is the first line, but be forgiving
                try:
                    obj = json.loads(line)
                except (json.JSONDecodeError, ValueError):
                    continue
                if isinstance(obj, dict) and obj.get("type") == "session_meta":
                    cwd = obj.get("payload", {}).get("cwd")
                    return cwd if isinstance(cwd, str) else None
                return None  # no meta on line 1 -> not a shape we understand
    except OSError:
        return None
    return None


# --- shared helpers ---------------------------------------------------------

def _newest(paths) -> Path | None:
    """Return the most recently modified path from ``paths``, or ``None``."""
    files = [p for p in paths if p.is_file()]
    if not files:
        return None
    return max(files, key=lambda p: p.stat().st_mtime)


def _clean_turn(role: str, content: object) -> tuple[str, str] | None:
    """Normalize a turn to ``(role, text)``, or ``None`` if it isn't real prose.

    Drops empty turns and synthetic command/tool turns (see
    :data:`_SKIP_PREFIXES`) that no agent's user actually typed.
    """
    text = _content_text(content).strip()
    if not text or text.startswith(_SKIP_PREFIXES):
        return None
    return role, text


def _content_text(content: object) -> str:
    """Join the text of a message's content, ignoring non-text blocks.

    Handles both a plain string and a list of blocks (``{"text": ...}``),
    covering Claude, Gemini and Codex message shapes alike.
    """
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        return " ".join(
            block["text"]
            for block in content
            if isinstance(block, dict) and isinstance(block.get("text"), str)
        )
    return ""


def _first_line(text: str) -> str | None:
    """Return the first non-blank line of ``text``, cleaned, or ``None``.

    Strips leading list/quote punctuation an agent sometimes prefixes (``- ``,
    ``: ``, ``• ``, ``> ``…) so the summary starts on a real word.
    """
    for line in text.splitlines():
        line = line.strip().lstrip("-:•*>–— ").strip()
        if line:
            return line
    return None
